# Generated by Django 3.2.25 on 2024-05-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
